name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Build
        run: cargo check --all-targets
      - name: Test
        run: cargo test
      - name: run all solutions
        run: .github/run.sh
      - name: clippy
        run: cargo clippy -- -D warnings
